name: Delete Old Workflows

on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * *

jobs:
  Cleaning:
    runs-on: ubuntu-22.04

    steps:
    - name: Delete Old Workflows
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 2
        keep_minimum_runs: 0
