name: Scheduled Build

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:     # 允许手动触发

jobs:
  trigger-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 定义需要定时编译的设备列表（按需增减）
        device:
          - model: jdcloud_ipq60xx_immwrt
            runs-on: ubuntu-22.04
          - model: zn_m2_libwrt_nowifi
            runs-on: ubuntu-22.04
          # 添加更多设备配置...